### ISSUE TITLE
`__` import being changed to `_`

### ISSUE THREAD

**Issue by iMarv** [renke/import-sort#75] opened 2018-12-21 13:58 UTC
Hi,

We are importing [`__` from ramda](https://ramdajs.com/docs/#__), which is being turned into a single `_` when applying the sort.

Using the most recent version of import-sort and the cli-tool. This is our config:

```json
  "importSort": {
    ".js": {
      "parser": "babylon",
      "style": "module"
    },
    ".ts": {
      "parser": "typescript",
      "style": "module"
    }
  },
```

If you need any additional info, let me know.

**Comment by renke** [comment] 2019-02-16 21:54
Hi @iMarv 

I couldn't reproduce this in the now released v6. If you still encounter this problem, just let me know. Closing for now.

**Closed by renke** 2019-02-16 21:54 UTC

**Comment by iMarv** [comment] 2019-02-22 14:06
Still happening for me in v6 @renke
