### ISSUE TITLE
Request: Always sort absolute imports before relative imports to comply with eslint-plugin-import by default

### ISSUE THREAD

**Issue by peterjuras** [renke/import-sort#9] opened 2016-11-21 09:32 UTC
Hi!

First of all thanks for this module, as you know it provides a solid foundation for the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=peterjuras.sort-imports).

I wanted to ask whether you would be open to adjusting the eslint (default) style for the parser to be in accordance with the default configuration of the popular [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb). The idea is that absolute imports always come before relative imports. Right now, the first order of the default sort style looks at the import method (unnamed import, default import, etc.) instead of the import origin.

Example:
Current default eslint sorting:

```js
import './foo';
import A from 'A';
```

Target default eslint sorting:

```js
import A from 'A';
import './foo';
```

What do you think? It seems that [import-sort-style-renke](https://github.com/renke/import-sort/tree/master/packages/import-sort-style-renke) is already quite close to the wished behavior, but I think it might be worth putting it into the default style.

**Comment by renke** [comment] 2017-06-25 16:56
Hi @peterjuras 

is this compatible with the default sort-imports rule from ESLint? Also, is this related to #17?

**Comment by alexanderbast** [comment] 2017-08-24 22:25
Hey,

the default sort-imports rule from ESLint and the import/first rule with absolute-first option from eslint-plugin-import are incompatible with each other, so i made https://github.com/alexanderbast/import-sort-style-absolute, which is compatible with both the StandardJS and Airbnb configs. :)

**Comment by jansauer** [comment] 2017-10-28 22:59
I had the same problem with the airbnb preset.
`"style": "eslint"` would list my import for global styled components at the top.
```
import './global-styles';

import { Route, Switch } from 'react-router';

import App from './containers/App';
import { BrowserRouter } from 'react-router-dom';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';
import React from 'react';
import injectTapEventPlugin from 'react-tap-event-plugin';
import { render } from 'react-dom';
...
```
and linting then fails with
```
...
   3:31  error  Absolute imports should come before relative imports  import/first
   5:30  error  Absolute imports should come before relative imports  import/first
...
```

@alexanderbast your sort style works perfect and fixes that; Thx a lot

**Comment by renke** [comment] 2017-12-02 18:30
I am closing this for now. I will have another look at the `eslint` style in the future, but custom plugins will probably be out of scope.

**Closed by renke** 2017-12-02 18:30 UTC

**Comment by joe-fenton** [comment] 2018-07-25 16:38
I'm not sure I understand what the resolution to this issue is? Is the cause a plugin to eslint? The automatic sort was working for me, but I just tried using react-boilerplate and now when I save files I get the linting error. I'm going to have to disable the sort-imports until I figure out a solution
